name: "Scheduled jobs"
on:
  schedule:
    - "0 */2 * * *"
jobs:
  post-art:
    needs: create-envfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with:
          working-directory: "./"
          stack-yaml: "stack.yaml"
          test: false
          ghc-version: "9.2.8" # Exact version of ghc to use
          cabal-version: "3.6.2.0"
      - name: "Creating .env"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: "Build and run"
        run: stack build && stack exec botinari-exe
